### ISSUE TITLE
Please bump version of `data-default-class`

### ISSUE THREAD

**Issue by winterland1989** [trskop/data-default-extra#1]
`data-default-class` is >= 0.1 for some time, I'd like to ask you to relax version bound in all your packages, otherwise they will not be compatible with latest `data-default-class` and `data-default`.

**Comment by liskin** [comment]
Fixed in #2. Peter edited the bounds on hackage and will possibly release a version that doesn't depend on data-default-instances-base (which isn't in lts-7) later.

**Comment by trskop** [comment]
At the moment I'm working on `data-default-extra` and `data-default-instances-new-base`. Those need little more then just bumping upper bounds.

**Comment by liskin** [comment]
To build with lts-7, yeah, but to build with cabal/hackage, those raised bounds work just fine. Or did I miss something?

**Comment by trskop** [comment]
You understand it correctly, but the LTS 7.* is a concern for me, and so I'm using this issue to resolve it.

**Comment by liskin** [comment]
Okay. As long as the end result is a list of package names/versions on hackage that I can put in stack.yaml/extra-deps tomorrow, I'll be happy. Thanks. :-)

**Comment by trskop** [comment]
I've released `data-default-extra-0.1.0` and `data-default-instances-new-base-0.0.2`. This should fix issues with LTS 7.*. I've tested it with LTS 5.18, 6.27 and 7.14.

**Comment by liskin** [comment]
It works! ♥

**Comment by winterland1989** [comment]
thanks！
